global_frame: odom
rolling_window: true

inflation_layer:
  inflation_radius:     0.25

plugins:
  - {name: obstacle_layer,                  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,                 type: "costmap_2d::InflationLayer"}
